//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils_Circulares.PlantillaCorreo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plantilla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plantilla() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils_Circulares.PlantillaCorreo.Plantilla", typeof(Plantilla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot; /&gt;
        ///  &lt;title&gt;Nueva circular publicada&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin:0; padding:0; background-color:#f4f6f8;&quot;&gt;
        ///  &lt;!-- Preheader (texto invisible que se ve en preview de Gmail) --&gt;
        ///  &lt;div style=&quot;display:none; font-size:1px; color:#f4f6f8; line-height:1px; max-height:0; max-width:0; opacity:0; overflow:hidden;&quot;&gt;
        ///    Se ha publicado una nueva circular en el sist [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Plantilla1 {
            get {
                return ResourceManager.GetString("Plantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string html = @&quot;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;es&apos;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&apos;UTF-8&apos;&gt;
        ///&lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///&lt;style&gt;
        ///    body {
        ///        margin: 0;
        ///        padding: 0;
        ///        background-color: #f4f6f9;
        ///        font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///    }
        ///
        ///    .container {
        ///        max-width: 600px;
        ///        margin: 40px auto;
        ///        background: #ffffff;
        ///        border-radius: 12px;
        ///        overflow: hidden;
        ///        box-shado [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PlantillaRecuperacionContrasena {
            get {
                return ResourceManager.GetString("PlantillaRecuperacionContrasena", resourceCulture);
            }
        }
    }
}
